[package]
name = "rbot"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
pretty_env_logger = "0.5.0"
reqwest = "0.12.23"
teloxide = { version = "0.17.0", features = ["macros"] }
teloxide_tests = "0.4.0"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
