[package]
name = "rbot"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
pretty_env_logger = "0.5.0"
reqwest = "0.12.15"
teloxide = { version = "0.15.0", features = ["macros"] }
teloxide_tests = "0.3.0"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
